routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontEnd\HomeController@index')->name('home');
Route::get('student/{id}', 'FrontEnd\HomeController@view')->name('student_view');
// Route::get('image/{file_path}', 'FrontEnd\HomeController@getPubliclyStorgeFile')->name('show_image');
Route::post('image/process', 'FrontEnd\HomeController@generateWatermarkImage');
Route::get('image/process', 'FrontEnd\HomeController@showGenerator');
Route::post('register', 'FrontEnd\StudentController@store')->name('register');

Route::group([
    'as'            => 'admin.',
    'prefix'        => 'admin',
    'namespace'     => 'Admin',
    'middleware'    => 'guest'
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
});

Route::group([
    'as'            => 'admin.dashboard.',
    'prefix'        => 'admin/dashboard',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'DashboardController@index')->name('index');
    Route::delete('trash/{id}', 'DashboardController@Trash')->name('trash');
    Route::get('restore/{id}', 'DashboardController@Restore')->name('restore');
    Route::get('export', 'DashboardController@export')->name('export');
    Route::get('getdrwawing/{st_id}', 'DashboardController@Drawing')->name('get_drawing');
    Route::get('update_stage/{st_id}', 'DashboardController@UpdateStage')->name('update_stage');
    Route::get('resubmit', 'DashboardController@resubmit');
    Route::get('edit/{id}', 'DashboardController@edit')->name('edit_drawing');
    Route::post('rotate-image', 'DashboardController@RotateImage');
    Route::post('watermark-image', 'DashboardController@WatermarkImage');
});



Route::post('admin/logout', 'Admin\LoginController@logout') ->name('admin.logout');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User;
use Illuminate\Database\Eloquent\SoftDeletes;
use Image;

class Student extends User
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'student_id',
        'name',
        'date_of_birth',
        'parent_name',
        'contact',
        'stage',
        'email',
        'age_group',
        'file_path',
        'school',
        'terms',
        'address',
    ];

    public function getWaterMarkImageAttribute()
    {
        $public_path  = asset('images/placeholder.png');

        if(file_exists(public_path($this->file_path))){
            $file_info   = pathinfo(asset($this->file_path));
            $wm_image = public_path('drawings/'.$this->student_id.'/1.'.$file_info['extension']);
            if (file_exists($wm_image)) {
                return asset('drawings/'.$this->student_id.'/1.'.$file_info['extension']);
            }
        }

        return $public_path;
    }
}

app/Http/Controllers/FrontEnd/CompetitionOneController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Models\Result;
use App\Http\Controllers\Controller;

class CompetitionOneController extends Controller
{
    /**
     * Show competition one page
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $results = Result::whereHas('submission', function ($query) {
            $query->where(['competition' => 2]);
        })->with([
            'submission:id,entry_id',
            'submission.entry:id',
            'submission.entry.students:id,name,university,avatar'
        ])->limit(3)->get(['id', 'submission_id']);

        return view('frontend.competitionOne', compact('results'));
    }
}

app/Http/Controllers/FrontEnd/CompetitionTwoController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Models\Result;
use App\Http\Controllers\Controller;

class CompetitionTwoController extends Controller
{
    /**
     * Show competition two page
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $results = Result::whereHas('submission', function ($query) {
            $query->where(['competition' => 1]);
        })->with([
            'submission:id,entry_id',
            'submission.entry:id',
            'submission.entry.students:id,name,university,avatar'
        ])->limit(3)->get(['id', 'submission_id']);

        return view('frontend.competitionTwo', compact('results'));
    }
}

app/Http/Controllers/FrontEnd/HomeController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Http\Controllers\Controller;
use App\Models\Student;
use Symfony\Component\HttpFoundation\Request;
use Illuminate\Support\LazyCollection;
use Intervention\Image\Facades\Image;

class HomeController extends Controller
{
    /**
     * Show homepage.
     *
     * @return \Illuminate\View\View
     */
    public function index(Request $request)
    {
        $students = Student::orderBy('created_at', 'asc');
        $student_count = Student::count();

        if ($request->has('age_group') && $request->age_group !== null) {
            $students->where('age_group', $request->age_group);
        }

        if ($request->has('find') && $request->find !== null) {
            $students->where('name', 'like', '%' . $request->find . '%')
            ->orWhere('contact', $request->find)
            ->orWhere('email', $request->find)
            ->orWhere('student_id', $request->find);
        }

        $students = $students->skip($request->offset ?? 0)->take($request->take ?? 12)->get();
        $age_groups = config('properties.age_groups', []);

        if ($request->ajax() && $students) {

            $response['data'] = $students->toArray();
            $response['offset'] = $request->offset;
            $response['take'] = $request->take;

            return $response;
        }

        return view('frontend.reuslts', compact('students', 'age_groups', 'student_count'));
    }

    public function view($student_id)
    {

        $response['student'] = Student::findOrfail($student_id);
        $response['success'] = true;
        $response['view'] =  view('frontend.model', ['student' => $response['student']])->render();

        return $response;
    }


    public function showGenerator()
    {
        return view('frontend.image_process');
    }


    public function generateWatermarkImage(Request $request)
    {
        $students = Student::skip($request->offset)->take($request->take)->get();
        $count = Student::count();

        if ($request->take >= $count) {
            return ['complete' => true];
        }

        $x = 0;

        foreach ($students as $key => $student) {

                if (is_readable(public_path($student->file_path))) {
                    $file_info   = pathinfo(public_path($student->file_path));
                    $allowed_mie_types = ['jpeg', 'jpg', 'png', 'gif'];

                if ($file_info && in_array($file_info['extension'], $allowed_mie_types) ) {
                    $make_img    = Image::make(public_path($student->file_path));
                    $full_path   = public_path($student->file_path);

                    if (!file_exists($full_path)) {
                        $make_img->text('Arunalu Siththam '.date('Y'), $make_img->width() - 260 , $make_img->height()-30, function($font) {
                            $font->file(public_path('assets/fonts/nunito-semibold-webfont.woff'));
                            $font->size(22);
                            $font->color('#ffff');
                            $font->align('left');
                            $font->valign('top');
                        });
                        $make_img->save($full_path, 90);
                    }
                }
                }




        }

        $offset = $request->take;
        $take   = $request->take + 50;


        if($take > $count){
            $take = $count - $request->take + $offset;
        }


        $next_record_details = ['offset' => $offset , 'take' => $take];



        return  $next_record_details;

        return ['complete' => true];

    }

}

app/Http/Controllers/FrontEnd/StudentController.php
<?php

namespace App\Http\Controllers\FrontEnd;

use App\Models\Result;
use App\Http\Controllers\Controller;
use App\Http\Requests\Students\RegisterRequest;
use Illuminate\Support\Facades\Mail;
use App\Mail\StudentRegistered;
use App\Models\Student;
use Carbon;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;
use Response;

class StudentController extends Controller
{
    /**
     * Show competition one page
     *
     * @return \Illuminate\View\View
     */


    public function store(RegisterRequest $request)
    {
        $now = Carbon\Carbon::now();
        $data = $request->all();
        $status = true;
        $data['age_group'] = null;
        $data['file_path'] = null;
        $age_groups = config('properties.age_groups');

        $student_id = 'CAS'.date('Y').'-'.$now->format('mdhis');
        $age = Carbon\Carbon::parse($request->date_of_birth)->age;

        foreach ($age_groups as $key => $group) {
            $ages = range($group['from'], $group['to']);
            in_array($age , $ages) ? $data['age_group']  = $key : null;
        }

        if($data['age_group'] == null){
            $status = false;
            $response['errors']['date_of_birth'] =  [0 =>'The date of birth must be in range of 4 - 16 years old'];
            return response()->json($response, 422);
        }

        if($request->has('drawing') && $request->file('drawing') !== null){
            $data['file_path'] = $request->file('drawing')->storeAs(
                'drawings/'.$age_groups[$data['age_group']]['name'], $student_id.'.'.$request->file('drawing')->extension()
            );
        }

        if($data['file_path'] == null){
            $status = false;
            $response['errors']['drawing'] =  [0 =>'Please upload your drawing'];
            return response()->json($response, 422);
        }

        $data['student_id'] = $student_id;

        if($status == true){
            if($student = Student::create($data)){
                Mail::to($student->email)->send(new StudentRegistered($student));
                $request->session()->flash('success' , 'Your drawing has been submitted');
            }
        }else{
            $request->session()->flash('error' , 'Oops. Something went wrong. try again!');
        }

        return $status;

    }



}

resources/views/frontend/image_process.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Generate Watermark</title>
</head>
<body>

    <button onclick="InnitiateGenerate('50')">Generate</button>
    <script src="{{asset('assets/js/lib.js')}}"></script>

    <div class="generated">
        <ul class="gn_count">

        </ul>
    </div>

    <script>

        function InnitiateGenerate(amount){
            $('.gn_count').append("<li>start Generating !</li>")
            generate(0, amount)
        }

        function generate(offset, take){

            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            $.ajax({
                method: 'POST',
                url: '/image/process',
                data:{offset:offset, take:take},
                error: function (data) {
                alert('Error')
                },
                success: function (response) {
                    loopGeneration(response)
                }
            });
        }

        function loopGeneration(response){
            if (!response.complete) {
                generate(response.offset, response.take)
                $('.gn_count').append("<li> Generated " + response.take+ "</li>")
            }else{
                $('.gn_count').append("<li>Completed !</li>")
            }
        }


    </script>
</body>
</html>

resources/views/frontend/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Arunalu</title>
    <link rel="stylesheet" href="{{ url('/assets') }}/css/lib.css">
    <link rel="stylesheet" href="{{ url('/assets') }}/css/winner/winner.css">
    <link rel="stylesheet" href="{{ url('/assets') }}/css/main.css">


</head>
<body class="onload">

   <main>
      @include('partials.aod-header')

      <section class="file-upload-sec">
         <div class="container__landing">
            <div class="wrap-file-upload">
               <div class="dopzone-sec">
                  <h4>Drawing</h4>
                  <div id="dropzone">
                     <form action="#" class="dropzone" id="DrawingDropzone">
                        <div class="wrap-drop">
                           <img src="{{ url('/assets') }}/images/dropzone/dropzone.png" class="file-icon" alt="file-icon">
                           <p class="drop-text"><img src="{{ url('/assets') }}/images/dropzone/clicp.png" alt="icon">
                              <span>Add file</span> or Drop files here</p>
                           <p class="file-size-details">File format: JPG Maximum size: 5MB</p>
                        </div>
                     </form>
                  </div>
               </div>
               <div class="contact-form-section">
                  <h4>Participant's Detail</h4>
                  <form id="contactForm" action="{{ route('register') }}" method="post" enctype="multipart/form-data" >
                     <div class="form-wrap">
                        <div class="sec">
                           <div class="input-wrapper">
                                <input type="text" name="name" id="name" required>
                                <label class="floatLablel" for="name">Participant's Name*</label>
                           </div>
                            <div class="input-wrapper">
                                <input type="text" name="school" id="school" required>
                                <label class="floatLablel" for="school">School Name*</label>
                            </div>
                            <div class="input-wrapper">
                                <input type="text" name="contact" id="contact" required>
                                <label class="floatLablel" for="contact">Contact No</label>
                            </div>
                            <div class="input-wrapper">
                                <input type="text" name="parent_name" id="parent_name" required>
                                <label class="floatLablel" for="parent_name">Parent/Guardian's Name</label>
                            </div>
                        </div>
                        <div class="sec">

                             <div class="input-wrapper">
                                <input type="text" name="date_of_birth" id="date_of_birth" class="data-pick" required>
                                <label class="floatLablel" for="date_of_birth">Participant's Date of Birth*</label>
                                <div class="date-content"></div>
                           </div>

                           <div class="input-wrapper">
                            <input type="text" name="address" id="address" required>
                            <label class="floatLablel" for="address">Postal Address</label>
                        </div>

                        <div class="input-wrapper">
                            <input type="text" name="email" id="email" required>
                            <label class="floatLablel" for="email">Email*</label>
                        </div>

                        </div>
                     </div>
                     <div class="wrp-form-btn">
                        <div class="form-btn-sec">
                            <div class="form-group">
                              <div class="check-box-wrap">
                                 <input type="checkbox" name="terms" id="terms" value="1">
                                 <label for="terms" class="ageement-lbl">I have read and agreed with the
                                     <a href="https://www.combank.lk/info/52" target="_blank">Terms & Conditions</a>.</label>
                              </div>
                            </div>
                            <div class="submit-btn-sec">
                               <button type="submit" class="submit-btn" id="submitArtwork">
                                 Submit Drawing
                                  <img src="{{ url('/assets') }}/images/dropzone/right-arrow.png" alt="">
                               </button>
                            </div>
                        </div>
                     </div>
                  </form>
               </div>
            </div>


            @include('partials.aod-footer-logos')
         </div>
      </section>
   </main>

  <script>
    var siteBaseUrl = '';
  </script>


  <script src="{{ url('/assets') }}/js/lib.js"></script>
  <script src="{{ url('/assets') }}/js/main.js"></script>
  <script src="{{ asset('js/sweetalert2.all.min.js') }}"></script>

    @if ($message = Session::get('error'))
    <script>
        Swal.fire({
        icon: 'error',
        title: 'Oops...',
        text: 'Something went wrong! Please try again',
        })
    </script>
    @endif
    @if ($message = Session::get('success'))
        <script>
            Swal.fire({
                title: 'Done!',
                text: "Your drawing has been successfully submitted",
                icon: 'success',
                confirmButtonColor: '#3085d6',
            })

        </script>
    @endif
</body>
</html>

resources/views/frontend/model.blade.php
   <!-- Modal -->

@if (isset($student))
<div class="modal fade" id="DrawingView" tabindex="-1" aria-labelledby="DrawingViewLabel" aria-hidden="true">

    <div class="modal-dialog modal-xl">

        <div class="modal-content">

            {{-- <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" onclick="closeButton()"></button>
            </div> --}}

            {{-- <header>
                <div class="container__landing">
                    <div class="header">
                        <a href="{{ route('home') }}" class="link">
                            <img src="{{ url('/assets') }}/images/header/left-arrow.png" alt="icon">
                            Back to Arunalu Sithtam
                        </a>
                        <img src="{{ url('/assets') }}/images/banner/ban-flow-1.png" alt="image"
                            class="fl-5">
                        <img src="{{ url('/assets') }}/images/header/combank-log.png" alt="logo"
                            class="combank-logo">
                    </div>
                </div>
            </header> --}}


            <div class="modal-body">

                <section class="single-winner-sec">
                    <div class="container__landing">

                        <img src="{{ url('/assets') }}/images/banner/ban-flow-3.png" alt="image"
                            class="fl-6">
                        <img src="{{ url('/assets') }}/images/banner/ban-flow-1.png" alt="image"
                            class="fl-7">

                        <div class="col-12 winner-single-content">
                            <div class="card">
                                {{-- <span class="watermark-sub">Arunalu Siththam 2021</span> --}}
                                <div class="img-container">
                                    <img src="{{ $student->file_path }}" alt="{{ $student->name }}">
                                </div>
                            </div>
                        </div>

                        <div class="col-12 winner-single-details">

                            <div class="row">

                                <div class="col-lg-4 col-md-4 col-sm-12 ps-4 winner-name">
                                    <h6 class="ws-title">Name:<h6>
                                            <h5 class="ws-description">{{ $student->name }}<h5>
                                </div>

                                <div class="col-lg-4 col-md-4 col-sm-12 ps-4 winner-school">
                                    <h6 class="ws-title">School Name:<h6>
                                            <h5 class="ws-description"> {{ $student->school }}<h5>
                                </div>

                                {{-- <div class="col-lg-4 col-md-4 col-sm-12 ps-4 social-share">
                                    <h6 class="ws-title">Share<h6>

                                            <div class="social_media">

                                                <a href="https://www.facebook.com/sharer/sharer.php?u={{ route('student_view', $student->id) }}"
                                                    target="_blank"><i class="fab fa-facebook ps-0"></i></a>
                                                <a href="https://www.instagram.com/?url=https:{{ route('student_view', $student->id) }}"
                                                    target="_blank"><i class="fab fa-instagram"></i></a>
                                                <a href="https://twitter.com/share?url={{ route('student_view', $student->id) }}"
                                                    target="_blank"><i class="fab fa-twitter"></i></a>
                                                <a href="https://wa.me/?text={{ route('student_view', $student->id) }}"
                                                    target="_blank"><i class="fab fa-whatsapp"></i></a>
                                                <a href="http://pinterest.com/pin/create/link/?url={{ route('student_view', $student->id) }}"
                                                    target="_blank"><i class="fab fa-pinterest"></i></a>
                                            </div>

                                </div> --}}

                            </div>
                        </div>

                    </div>
                </section>
            </div>

            {{-- <section class="file-upload-sec">
                <div class="container__landing">

                    @include('partials.aod-footer-logos')
                </div>
            </section> --}}

        </div>
    </div>
</div>
@endif

   <!-- Modal -->

resources/views/frontend/new_link_2.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{asset('assets/css/winner/winner.css')}}">
    <link rel="stylesheet" href="{{asset('assets/css/lib/lib.css')}}">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
        integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <title>Arunalu Siththam {{date("Y")}}</title>

</head>
<body class="onload p-landing">
    <main>
        <header>
            <div class="container__landing">
                <div class="header">
                    <a href="{{route('home')}}" class="link">
                        <img src="{{ url('/assets') }}/images/header/left-arrow.png" alt="icon">
                        Back
                    </a>
                    <img src="{{ url('/assets') }}/images/banner/ban-flow-1.png" alt="image" class="fl-5">
                    <img src="{{ url('/assets') }}/images/header/combank-log.png" alt="logo" class="combank-logo">
                </div>
            </div>
        </header>

        <section class="single-winner-sec">
            <div class="container__landing">

                <img src="{{ url('/assets') }}/images/banner/ban-flow-3.png" alt="image" class="fl-6">
                <img src="{{ url('/assets') }}/images/banner/ban-flow-1.png" alt="image" class="fl-7">

                <div class="col-12 winner-single-content">
                    <div class="card">
                         {{-- <span class="watermark-sub">Arunalu Siththam 2021</span> --}}
                        <div class="img-container">
                            <img src="{{ $student->water_mark_image}}" alt="{{$student->name}}">
                        </div>
                    </div>
                </div>

                <div class="col-12 winner-single-details">

                    <div class="row">

                        <div class="col-lg-4 col-md-4 col-sm-12 ps-4 winner-name">
                            <h6 class="ws-title">Name:<h6>
                                    <h5 class="ws-description">{{$student->name}}<h5>
                        </div>

                        <div class="col-lg-4 col-md-4 col-sm-12 ps-4 winner-school">
                            <h6 class="ws-title">School Name:<h6>
                                    <h5 class="ws-description">{{$student->school}}<h5>

                        </div>

                        <div class="col-lg-4 col-md-4 col-sm-12 ps-4 social-share">
                            <h6 class="ws-title">Share<h6>

                                    <div class="social_media">

                                        <a href="https://www.facebook.com/sharer/sharer.php?u={{ route('student_view', $student->id) }}"  target="_blank"><i class="fab fa-facebook ps-0"></i></a>
                                        <a href="https://www.instagram.com/?url=https:{{ route('student_view', $student->id) }}"  target="_blank"><i class="fab fa-instagram"></i></a>
                                        <a href="https://twitter.com/share?url={{ route('student_view', $student->id) }}"  target="_blank"><i class="fab fa-twitter"></i></a>
                                        <a href="https://wa.me/?text={{ route('student_view', $student->id) }}"  target="_blank"><i class="fab fa-whatsapp"></i></a>
                                        <a href="http://pinterest.com/pin/create/link/?url={{ route('student_view', $student->id) }}"  target="_blank"><i class="fab fa-pinterest"></i></a>
                                    </div>

                        </div>

                    </div>
                </div>

            </div>
        </section>

        <section class="file-upload-sec">
            <div class="container__landing">

                @include('partials.aod-footer-logos')
            </div>
        </section>
    </main>

    <script src="{{asset('assets/js/lib.js')}}"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>

<script>
    document.addEventListener("contextmenu", function (e) {
        e.preventDefault();
    }, false);
</script>

</body>

</html>

resources/views/frontend/reuslts.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Arunalu</title>
    <link rel="stylesheet" href="{{ url('/assets') }}/css/lib.css">
    <link rel="stylesheet" href="{{ url('/assets') }}/css/winner/winner.css">
    <link rel="stylesheet" href="{{ url('/assets') }}/css/main.css">


</head>

<body class="onload">

    <main>
        @include('partials.aod-header')

        <section>
            <p class="text-center">Time period given for submission of drawings is over. <br> Stay tuned for announcement of winners. </p>
            <div class="container__landing">
                @include('partials.aod-footer-logos')
            </div>
        </section>

    </main>

    <script>
        var siteBaseUrl = '';
    </script>


    <script src="{{ url('/assets') }}/js/lib.js"></script>
    <script src="{{ url('/assets') }}/js/main.js"></script>
    <script src="{{ asset('js/sweetalert2.all.min.js') }}"></script>

    @if ($message = Session::get('error'))
    <script>
        Swal.fire({
        icon: 'error',
        title: 'Oops...',
        text: 'Something went wrong! Please try again',
        })
    </script>
    @endif
    @if ($message = Session::get('success'))
    <script>
        Swal.fire({
                title: 'Done!',
                text: "Your drawing has been successfully submitted",
                icon: 'success',
                confirmButtonColor: '#3085d6',
            })

    </script>
    @endif
</body>

</html>