routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'FrontEnd\HomeController@index')->name('home');
Route::get('student/{id}', 'FrontEnd\HomeController@view')->name('student_view');
// Route::get('image/{file_path}', 'FrontEnd\HomeController@getPubliclyStorgeFile')->name('show_image');
Route::post('image/process', 'FrontEnd\HomeController@generateWatermarkImage');
Route::get('image/process', 'FrontEnd\HomeController@showGenerator');
Route::post('register', 'FrontEnd\StudentController@store')->name('register');

Route::group([
    'as'            => 'admin.',
    'prefix'        => 'admin',
    'namespace'     => 'Admin',
    'middleware'    => 'guest'
], function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
});

Route::group([
    'as'            => 'admin.dashboard.',
    'prefix'        => 'admin/dashboard',
    'namespace'     => 'Admin',
    'middleware'    => 'auth:admin'
], function () {
    Route::get('', 'DashboardController@index')->name('index');
    Route::delete('trash/{id}', 'DashboardController@Trash')->name('trash');
    Route::get('restore/{id}', 'DashboardController@Restore')->name('restore');
    Route::get('export', 'DashboardController@export')->name('export');
    Route::get('getdrwawing/{st_id}', 'DashboardController@Drawing')->name('get_drawing');
    Route::get('update_stage/{st_id}', 'DashboardController@UpdateStage')->name('update_stage');
    Route::get('resubmit', 'DashboardController@resubmit');
    Route::get('edit/{id}', 'DashboardController@edit')->name('edit_drawing');
    Route::post('rotate-image', 'DashboardController@RotateImage');
    Route::post('watermark-image', 'DashboardController@WatermarkImage');
});



Route::post('admin/logout', 'Admin\LoginController@logout') ->name('admin.logout');

resources/views/layouts/alerts.blade.php
{{-- @if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $message }}</strong>
</div>
@endif
@if ($message = Session::get('error'))
<div class="alert alert-danger alert-block">
	<button type="button" class="close" data-dismiss="alert">×</button>
	<strong>{{ $message }}</strong>
</div>
@endif --}}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0" />
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <meta http-equiv='cache-control' content='no-cache'>
    <meta http-equiv='expires' content='0'>
    <meta http-equiv='pragma' content='no-cache'>

    <title>Arunalu Siththam - {{date('Y')}} | @yield('title')</title>

    <link rel="stylesheet" href="{{  asset('css/materialize.min.css') }}">
    <link rel="stylesheet" href="{{  asset('css/app.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    @stack('styles')
</head>

<body>
    <div class="main-container">
        @include('layouts.sidebar')

        <main id="main-section" role="main">
            @include('admin.includes.alerts')
            @yield('content')

            @include('layouts.footer')
        </main>
    </div>

    {{-- <script src="{{ asset('js/jquery.slim.min.js') }}"></script> --}}
    <script src="{{ asset('js/materialize.min.js') }}"></script>
    <script src="{{ asset('assets/js/jquery-3.6.0.min.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>

    @stack('scripts')
</body>

</html>

resources/views/layouts/footer.blade.php
<!-- <footer>
   <p>&copy;2020. PCC Student Design Competition Submission Portal. All rights reserved. </p>
</footer> -->

resources/views/layouts/sidebar.blade.php
@php
    $route = Route::currentRouteName();
@endphp

<section id="sidebar">
    <div class="logo-sec">
        <img src="{{ asset('assets/images/header/combank-log.png') }}" alt="" style="width: 114px;">

        <span class="text-uppercase">Arunalu Siththam {{date("Y")}}</span>
    </div>

    @auth('admin')
        <div class="page-link">
            <ul>
                <li><a class="{{ Str::contains($route, 'dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard.index') }}">COMPETITORS </a></li>
            </ul>
        </div>
    @endauth

    <div class="portlogo">
        <img src="{{ asset('assets/images/banner/caract-1.png') }}" alt="">
    </div>
</section>